"""removed user_id from documents

Revision ID: e10bb0e73dea
Revises: 846a616079bc
Create Date: 2025-05-21 18:25:57.341989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e10bb0e73dea'
down_revision: Union[str, None] = '846a616079bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('documents_user_id_fkey', 'documents', type_='foreignkey')
    op.drop_column('documents', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('documents_user_id_fkey', 'documents', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
