"""added stars and ingestion columns in documents model 

Revision ID: f257f4eb01f7
Revises: 28c74f000ebd
Create Date: 2025-05-25 03:52:39.839958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f257f4eb01f7'
down_revision: Union[str, None] = '28c74f000ebd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('ingestion_status', sa.String(), nullable=False))
    op.add_column('users', sa.Column('stars', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('views', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'views')
    op.drop_column('users', 'stars')
    op.drop_column('documents', 'ingestion_status')
    # ### end Alembic commands ###
