"""bugfix: move stars and views column to documnets model

Revision ID: f354bd752436
Revises: 037f93aa80e5
Create Date: 2025-05-25 20:52:58.790176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f354bd752436'
down_revision: Union[str, None] = '037f93aa80e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('stars', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('views', sa.Integer(), nullable=True))
    op.drop_column('users', 'stars')
    op.drop_column('users', 'views')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('views', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('stars', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('documents', 'views')
    op.drop_column('documents', 'stars')
    # ### end Alembic commands ###
