name: Continuous Integration

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  run-backend-tests:
    name: Backend CI Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11.3
      uses: actions/setup-python@v3
      with:
        python-version: "3.11.3"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Use the sample .env file
      run: cp .env.sample .env
    - name: Testing Users endpoints
      run: pytest app/modules/users/tests
    - name: Testing Documents endpoints
      run: pytest app/modules/documents/tests
    - name: Testing End to End
      run: pytest tests

  update-submodule-in-main:
    name: Update Submodule Ref in Main Repo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4
        with:
          repository: ctadel/ctadel-library
          token: ${{ secrets.PAT }}
          ref: master
          submodules: true

      - name: Configure git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create/update sync/backend branch
        run: |
          git checkout -B sync/backend

      - name: Update submodule
        run: |
          git submodule update --remote backend
          git add backend

      - name: Check for submodule pointer change
        id: check_changes
        run: |
          if ! git diff --cached --exit-code; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          git commit -m "Actions: update backend submodule"
          git push origin sync/backend --force

      - name: Create or update PR to master
        if: steps.check_changes.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT }}
          title: "Update backend submodule"
          body: |
            This PR updates the backend submodule to the latest commit.
            It is automatically generated by GitHub Actions.
          base: master
          branch: sync/backend
