name: Continuous Integration

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  run-backend-tests:
    name: Backend CI Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11.3
      uses: actions/setup-python@v3
      with:
        python-version: "3.11.3"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Use the sample .env file
      run: cp .env.sample .env
    - name: Testing Users endpoints
      run: pytest app/modules/users/tests
    - name: Testing Documents endpoints
      run: pytest app/modules/documents/tests
    - name: Testing End to End
      run: pytest tests

  update-submodule-in-main:
    name: Update Backend Submodule and Create PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          submodules: true

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update backend submodule
        run: |
          git submodule update --remote backend
          git add backend

      - name: Commit changes if any
        id: commit
        run: |
          if ! git diff --cached --quiet; then
            git commit -m "Actions: update backend submodule"
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT

      - name: Push branch
        if: steps.commit.outputs.changes == 'true'
        run: |
          git checkout -B sync/backend
          git push --force origin sync/backend

      - name: Create or update PR
        if: steps.commit.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT }}
          title: "Update backend submodule"
          body: |
            This PR updates the backend submodule to the latest commit.
            It is automatically generated by GitHub Actions.
          base: master
          branch: sync/backend
          draft: false
